drop table if exists tags;
drop table if exists item_notes;
drop table if exists items;
drop table if exists users;

create table if not exists users
(
    id                bigint generated by default as identity
        primary key,
    first_name        varchar(100),
    email             varchar(55),
    last_name         varchar(100),
    state             varchar(15),
    registration_date timestamp
);


create table if not exists items
(
    id      bigint generated by default as identity
        primary key,
    user_id bigint not null
        constraint items_users_id_fk
            references users,
    url     varchar(255)
);

create table if not exists tags
(
    id      bigint generated by default as identity
        constraint tags_pk
            primary key,
    name    varchar(50),
    item_id bigint
        constraint tags_items_id_fk
            references items
);


create table if not exists item_notes
(
    id         bigint generated by default as identity
        constraint item_notes_pk
            primary key,
    note       varchar(2000),
    created_at timestamp,
    item_id    bigint not null
        constraint item_notes_items_id_fk
            references items
);

